# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{fourmer}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Tim Olshansky}]
  s.date = %q{2011-10-06}
  s.description = %q{An easy to use library for interacting with the Foursquare Merchant API}
  s.email = %q{tim.olshansky@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".autotest",
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/fourmer.rb",
    "lib/foursquare/base.rb",
    "lib/foursquare/campaign.rb",
    "lib/foursquare/campaigns.rb",
    "lib/foursquare/consumer.rb",
    "lib/foursquare/errors.rb",
    "lib/foursquare/model.rb",
    "lib/foursquare/requests.rb",
    "lib/foursquare/special.rb",
    "lib/foursquare/specials.rb",
    "lib/foursquare/timeseries.rb",
    "lib/foursquare/venue.rb",
    "lib/foursquare/venue_group.rb",
    "lib/foursquare/venue_groups.rb",
    "lib/foursquare/venue_stats.rb",
    "lib/foursquare/venues.rb",
    "test/helper.rb",
    "test/test_base.rb",
    "test/test_campaign.rb",
    "test/test_campaigns.rb",
    "test/test_consumer.rb",
    "test/test_errors.rb",
    "test/test_fourmer.rb",
    "test/test_model.rb",
    "test/test_special.rb",
    "test/test_specials.rb",
    "test/test_timeseries.rb",
    "test/test_venue.rb",
    "test/test_venue_group.rb",
    "test/test_venue_groups.rb",
    "test/test_venue_stats.rb",
    "test/test_venues.rb"
  ]
  s.homepage = %q{http://github.com/timols/fourmer}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{An unofficial wrapper for the Foursquare Merchant API}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, [">= 0"])
      s.add_runtime_dependency(%q<hashie>, [">= 1.1.0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<httparty>, [">= 0"])
      s.add_dependency(%q<hashie>, [">= 1.1.0"])
      s.add_dependency(%q<mocha>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<httparty>, [">= 0"])
    s.add_dependency(%q<hashie>, [">= 1.1.0"])
    s.add_dependency(%q<mocha>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

