$LOAD_PATH << File.dirname(__FILE__)

require 'rubygems'
require 'hashie'
require 'httparty'
require 'foursquare/requests'
require 'foursquare/base'
require 'foursquare/model'
require 'foursquare/campaigns'
require 'foursquare/campaign'
require 'foursquare/consumer'
require 'foursquare/errors'
require 'foursquare/specials'
require 'foursquare/special'
require 'foursquare/timeseries'
require 'foursquare/venue_groups'
require 'foursquare/venue_group'
require 'foursquare/venues'
require 'foursquare/venue'
require 'foursquare/venue_stats'
